// export { default as Banner } from './banner/banner'
export { default as Header } from './core/Header'
export { default as HeaderAlt } from './core/HeaderAlt'
export { default as Project } from './projects/Project'
// export { default as Carousel } from './carousel/carousel'
export { default as HomeImage } from './home/Image'
